import re
from collections import OrderedDict
from io import BytesIO

from docx import Document


def create_response(message, code=200, data=None):
    """All responses from the API should be generated by this function to keep the
    responses consistant.
    """
    return {"message": message, "code": code, "data": data}
